In [1]:
# importing the necessary libries 
import pandas as pd
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [2]:
df1 = 'C:/Users/User/Downloads/Malrias.xls'

In [3]:
df=pd.read_excel(df1)

In [4]:
df = df.drop('Unnamed: 0', axis=1)

In [5]:
df

,Country Name,Year,Country Code,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)",...,Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude,geometry
0,Nigeria,2008,NGA,424.66,143079,6.0,33.2,3.200000,17.85,13.45,...,4.79,59.03,44.52,79.32,33.10,29.89,37.59,9.081999,8.675277,POINT (9.081999 8.675276999999999)
1,Sierra Leone,2008,SLE,413.85,176356,26.0,27.8,5.200000,6.76,3.97,...,3.40,49.33,35.61,71.64,12.53,6.29,22.69,8.460555,-11.779889,POINT (8.460554999999999 -11.779889)
2,Nigeria,2010,NGA,398.90,551187,29.4,49.1,5.700000,18.40,13.98,...,4.74,61.81,46.96,81.10,34.31,30.10,39.78,9.081999,8.675277,POINT (9.081999 8.675276999999999)
3,Sierra Leone,2010,SLE,458.74,934028,30.3,62.1,17.542633,7.40,4.81,...,3.26,51.94,38.83,72.57,13.20,6.77,23.33,8.460555,-11.779889,POINT (8.460554999999999 -11.779889)
4,Nigeria,2011,NGA,372.56,0,16.4,44.6,5.953138,18.67,14.24,...,4.70,63.19,48.19,82.00,34.94,30.20,40.89,9.081999,8.675277,POINT (9.081999 8.675276999999999)
5,Nigeria,2013,NGA,328.65,0,16.6,32.7,7.100000,19.18,14.75,...,4.59,65.94,50.65,83.81,36.27,30.37,43.16,9.081999,8.675277,POINT (9.081999 8.675276999999999)
6,Sierra Leone,2013,SLE,432.70,1701958,49.0,48.3,20.700000,8.43,6.21,...,3.22,55.79,43.66,73.94,14.24,7.50,24.32,8.460555,-11.779889,POINT (8.460554999999999 -11.779889)
7,Nigeria,2015,NGA,296.08,7131972,43.6,41.2,21.400000,19.67,15.24,...,4.45,68.67,53.11,85.63,37.68,30.53,45.48,9.081999,8.675277,POINT (9.081999 8.675276999999999)
8,Sierra Leone,2016,SLE,391.33,1775306,44.1,57.0,31.100000,9.53,7.78,...,3.14,59.56,48.52,75.31,15.29,8.26,25.32,8.460555,-11.779889,POINT (8.460554999999999 -11.779889)

In [6]:
# Running Descriptive analysis of the dataset
df.describe()

,Year,"Incidence of malaria (per 1,000 population at risk)",Malaria cases reported,Use of insecticide-treated bed nets (% of under-5 population),Children with fever receiving antimalarial drugs (% of children under age 5 with fever),Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women),People using safely managed drinking water services (% of population),"People using safely managed drinking water services, rural (% of rural population)","People using safely managed drinking water services, urban (% of urban population)",People using safely managed sanitation services (% of population),...,Urban population (% of total population),Urban population growth (annual %),People using at least basic drinking water services (% of population),"People using at least basic drinking water services, rural (% of rural population)","People using at least basic drinking water services, urban (% of urban population)",People using at least basic sanitation services (% of population),"People using at least basic sanitation services, rural (% of rural population)","People using at least basic sanitation services, urban (% of urban population)",latitude,longitude
count,9.000000,9.00000,9.000000e+00,9.000000,9.00000,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,2011.555556,390.83000,1.379321e+06,29.044444,44.00000,13.099530,13.987778,10.492222,18.640000,19.697778,...,42.413333,4.032222,59.473333,45.561111,78.368889,25.728889,19.990000,33.617778,8.805802,-0.415908
std,2.877113,51.57802,2.264356e+06,14.549580,11.48956,9.827542,5.722267,4.692408,6.647507,7.485349,...,3.299625,0.746538,6.315451,5.584981,5.144838,11.395756,12.141631,9.479976,0.327530,10.780819
min,2008.000000,296.08000,0.000000e+00,6.000000,27.80000,3.200000,6.760000,3.970000,11.290000,10.780000,...,38.080000,3.140000,49.330000,35.610000,71.640000,12.530000,6.290000,22.690000,8.460555,-11.779889
25%,2010.000000,372.56000,1.430790e+05,16.600000,33.20000,5.700000,8.430000,6.210000,11.750000,12.190000,...,40.040000,3.260000,55.790000,43.660000,73.940000,14.240000,7.500000,24.320000,8.460555,-11.779889
50%,2011.000000,398.90000,5.511870e+05,29.400000,44.60000,7.100000,17.850000,13.450000,24.000000,25.570000,...,41.700000,4.450000,59.560000,46.960000,79.320000,33.100000,29.890000,37.590000,9.081999,8.675277
75%,2013.000000,424.66000,1.701958e+06,43.600000,49.10000,20.700000,18.670000,14.240000,24.210000,25.940000,...,44.370000,4.700000,63.190000,48.520000,82.000000,34.940000,30.200000,40.890000,9.081999,8.675277
max,2016.000000,458.74000,7.131972e+06,49.000000,62.10000,31.100000,19.670000,15.240000,24.500000,26.420000,...,47.840000,4.790000,68.670000,53.110000,85.630000,37.680000,30.530000,45.480000,9.081999,8.675277

In [7]:
# finding how many countries are involved in the dataset
df_CO = df['Country Name'].value_counts()
df_CO

Nigeria         5
Sierra Leone    4
Name: Country Name, dtype: int64

In [10]:
# Now we are finding the total case of malaria that has been reported in the countries from 2008-2016
# We first create a list showing the range of 2006 to 2017
years = list(map(str,range(2006,2017)))

In [21]:
# Grouping the incidence of total malarai from 2006-2016
yi=df['Malaria cases reported']
data = [go.Bar(x=years,y=yi)]
layout = go.Layout(title='Malaria Case from 2006 to 2017',
                   xaxis={'title':'Year'},
                   yaxis={'title':'Cases Reported'})

In [22]:
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='BArchart.html')

'BArchart.html'